[package]
name = "gamegirl-egui"
default-run = "gamegirl_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gamegirl_bin"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common", features = ["serde_config", "serde"] }
gamegirl = { path = "../gamegirl", features = [
    "ggc",
    "gga",
    "nds",
    "psx",
    "serde",
] }

eframe = { version = "0.23.0", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }
cpal = "0.15.2"
rfd = "0.12.0"
futures-executor = "0.3.28"
env_logger = "0.10.0"
log = "0.4"

serde = { version = "1.0.188" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-futures = "0.4.37"
cpal = { version = "0.15.2", features = ["wasm-bindgen"] }

# Disable the threaded PPU, wasm doesn't support std::thread
gga = { path = "../cores/gga", default-features = false }
nds = { path = "../cores/nds", default-features = false }


[features]
remote-debugger = ["gamegirl/remote-debugger"]
