[workspace]
members = [
    "common",
    "components/*",
    "cores/*",
    "gamegirl",
    "gamegirl-egui",
    "tests",
    "tests/tracing",
]
resolver = "2"

[profile.release]
debug = true
lto = true
panic = "abort"

[profile.dev]
opt-level = 1

[workspace.dependencies]
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_arrays = "0.1.0"
arrayvec = "0.7.4"
bitflags = "2.4.1"
modular-bitfield = "0.11"
bitmatch = "0.1.1"
glow = "0.12"
