[workspace]
members = ["common", "cores/*", "gamegirl", "gamegirl-egui", "tests", "tests/tracing"]
resolver = "2"

[profile.release]
debug = true
lto = true
panic = "abort"

[profile.dev]
opt-level = 1
