[package]
name = "nds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
gga = { path = "../gga" }

serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_arrays = "0.1.0"
log = "0.4.17"


[features]
default = ["threaded-ppu"]
instruction-tracing = []
threaded-ppu = ["gga/threaded-ppu"]
