[package]
name = "dynacore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
common = { path = "../../common" }
gamegirl = { path = "../../gamegirl", features = ["ggc", "gga"] }
once_cell = "1.19"
