[package]
name = "gga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }

serde = { version = "1.0.140", features = ["derive", "rc"], optional = true }
serde_arrays = { version = "0.1.0", optional = true }
arrayvec = { version = "0.7.2" }
log = "0.4.17"

elf_rs = "0.2.0"


[features]
default = ["threaded-ppu"]
threaded-ppu = []
serde = ["dep:serde", "dep:serde_arrays", "arrayvec/serde", "common/serde"]
