[package]
name = "gga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }

serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_arrays = "0.1.0"
arrayvec = { version = "0.7.2", features = ["serde"] }
log = "0.4.17"

elf_rs = "0.2.0"


[features]
default = ["threaded-ppu"]
instruction-tracing = []
threaded-ppu = []
