[package]
name = "gamerunner"
version = "0.1.0"
edition = "2021"

[dependencies]
gamegirl = { path = "../../gamegirl", features = ["ggc", "gga"] }
png = "0.17"
clap = { version = "4.0", features = ["derive"] }
zip = "2.1"
rayon = "1.5"
indicatif = "0.17"
