[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmatch = "0.1.1"
bitflags = "1.3.2"
arrayvec = { version = "0.7.2" }
log = "0.4.17"

serde = { version = "1.0.140", features = ["derive", "rc"], optional = true }
serde_arrays = { version = "0.1.0", optional = true }
bincode = { version = "1.3.3", optional = true }
zstd = { version = "0.11.2", default-features = false, optional = true }

[features]
serde = ["dep:serde", "dep:serde_arrays", "dep:bincode", "dep:zstd", "arrayvec/serde"]
serde_config = ["dep:serde"]
instruction-tracing = []
