[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_arrays = "0.1.0"
bincode = "1.3.3"
zstd = { version = "0.11.2", default-features = false }

bitmatch = "0.1.1"
bitflags = "1.3.2"
arrayvec = { version = "0.7.2", features = ["serde"] }
log = "0.4.17"
