[package]
name = "corebench-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
dynacore = { path = "../dynacore" }
eframe = { version = "0.26.2", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }
libloading = "0.8"
env_logger = "0.11.3"
rfd = "0.14.0"
futures-executor = "0.3.30"
notify = "6.1.1"
walkdir = "2"
