[package]
name = "gamegirl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
ggc = { path = "../cores/ggc" }
gga = { path = "../cores/gga" }
nds = { path = "../cores/nds" }
psx = { path = "../cores/psx" }
log = "0.4.17"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gdbstub = "0.6.2"
gdbstub_arch = "0.2.3"


[target.'cfg(target_arch = "wasm32")'.dependencies]
zstd = { version = "0.11.2", default-features = false, features = ["wasm"] }
web-sys = { version = "0.3.59", features = ["Storage", "Window"] }
base64 = "0.13.0"
