[package]
name = "gamegirl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
ggc = { path = "../cores/ggc", optional = true }
gga = { path = "../cores/gga", optional = true }
nds = { path = "../cores/nds", optional = true }
psx = { path = "../cores/psx", optional = true }
log = "0.4.20"

gdbstub = { version = "0.6.6", optional = true }
gdbstub_arch = { version = "0.2.4", optional = true }
glow = "0.12.3"


[target.'cfg(target_arch = "wasm32")'.dependencies]
zstd = { version = "0.12.4", default-features = false, features = ["wasm"] }
web-sys = { version = "0.3.64", features = ["Storage", "Window"] }
base64 = "0.21.4"

[target.'cfg(target_arch = "x86_64")'.dependencies]
gga = { path = "../cores/gga", optional = true }
nds = { path = "../cores/nds", optional = true }

[features]
serde = ["common/serde", "ggc/serde", "gga/serde", "nds/serde"]
remote-debugger = ["dep:gdbstub", "dep:gdbstub_arch"]
